### ISSUE TITLE
dev-python/ipython[notebook] missing dep on ipywidgets

### ISSUE THREAD

**Issue by jlec** [gentoo-science/sci#474]
```
 $ (0) ipython notebook
[W 12:52:06.777 NotebookApp] ipywidgets package not installed.  Widgets are unavailable.
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/ipython", line 5, in <module>
    start_ipython()
  File "/usr/lib64/python3.4/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/lib64/python3.4/site-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib64/python3.4/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib64/python3.4/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/usr/lib64/python3.4/site-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/usr/lib64/python3.4/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/usr/lib64/python3.4/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/traitlets/config/application.py", line 425, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/lib64/python3.4/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/lib64/python3.4/site-packages/notebook/notebookapp.py", line 1005, in initialize
    self.init_webapp()
  File "/usr/lib64/python3.4/site-packages/notebook/notebookapp.py", line 871, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/usr/lib64/python3.4/site-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib64/python3.4/site-packages/tornado/netutil.py", line 187, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
```

**Comment by kiwifb** [comment]
Chiming a bit late. If `ipywidgets` is required by the `notebook` (actually it looks like it is in spite of the documentation) why doesn't the `notebook` depend on `ipywidgets`? That would avoid the extra `REQUIRED_USE` line in the `ipython` ebuild and would probably be more correct in regards to dependencies.

**Comment by marbre** [comment]
@kiwifb To clarify, you would prefer my previous commit https://github.com/gentoo-science/sci/commit/379464943d2a72a6558b749ec0c6647a879f7fde. AFAIR I discussed this with @jlec in IRC and it seems better to solve this with commit https://github.com/gentoo-science/sci/commit/96ed940db8028ce80a3a80629921807337ad74e1.

**Comment by kiwifb** [comment]
@marbre I was unaware about other discussions so I don't really know the argument. I just stumbled upon all this when I found the dependencies to be bizarre on upgrading - in particular the use flag requirement.
I guess my own gut feeling is that the `notebook` needs to have all its dependencies and it looks to me that `ipywidgets` is one of them. I wouldn't have done what you did in https://github.com/gentoo-science/sci/commit/96ed940db8028ce80a3a80629921807337ad74e1. I would have added the dependency in the `notebook` ebuild. There is a scenario for example 
```
emerge -puDNv notebook
[ebuild  N    *] dev-python/ipython_genutils-9999::science  USE="{-test}" PYTHON_TARGETS="python2_7 python3_3 -python3_4" 0 KiB
[ebuild  N    *] dev-python/traitlets-9999::science  USE="-doc {-test}" PYTHON_TARGETS="python2_7 python3_3 -python3_4" 0 KiB
[ebuild  N    *] dev-python/jupyter_core-9999::science  USE="-doc {-test}" PYTHON_TARGETS="python2_7 python3_3 -python3_4" 0 KiB
[ebuild  N    *] dev-python/ipykernel-9999::science  USE="{-test}" PYTHON_TARGETS="python2_7 python3_3 -python3_4" 0 KiB
[ebuild  N    *] dev-python/nbformat-9999::science  USE="-doc {-test}" PYTHON_TARGETS="python2_7 python3_3 -python3_4" 0 KiB
[ebuild  N    *] dev-python/nbconvert-9999::science  USE="-doc {-test}" PYTHON_TARGETS="python2_7 python3_3 -python3_4" 0 KiB
[ebuild  N    *] dev-python/jupyter_client-9999::science  USE="{-test}" PYTHON_TARGETS="python2_7 python3_3 -python3_4" 0 KiB
[ebuild  N    *] dev-python/notebook-9999::science  USE="-doc {-test}" PYTHON_TARGETS="python2_7 python3_3 -python3_4" 0 KiB
```
So here two ebuild are not pulled: `ipython`, will the `notebook` work alone without the `ipython` base? `ipywidgets` again will things work without it.

It looks to me like the current chain for installing `ipython` components rely on you emerging `ipython` with the right useflags. Some components can probably stand alone but which ones? But may be I have all this backwards.

**Comment by marbre** [comment]
@kiwifb In general `notebook` has no dependecy on ipython: https://github.com/jupyter/notebook/blob/master/setup.py#L153.
At the moment `notebook` requires `ipykernel`. Further, additional languages and kernels are supported by jupyter (https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages). Thus notebook don't need `ipython`, depending on the language/kernel you want to use.

The [Big Split](http://blog.jupyter.org/2015/04/15/the-big-split/) didn't really made things easier at a first glance. So I am aware that not all dependencies might be correct. Anyway, I decided to merge into the master, because I didn't found any big issues are some weeks of productive use on my machines. So I really appreciate any feedback.

@jlec, your suggestion? Should I revert commit 96ed940?

**Comment by kiwifb** [comment]
I see the dependency is more subtle than I thought. I'll defer to @jlec's judgement, I just don't like the `REQUIRED_USE` line very much but it is economical in the `{,R}DEPEND` section.

**Comment by marbre** [comment]
Okay, this is finally solved as `ipython[notebook]` will required `ipywidgets` and the *wxwidgets* use flag will pull in `wxpython` independently. Thus, the `REQUIRED_USE` will be dropped.
