### ISSUE TITLE
Still having issues with eselect , lapack, and blas

### ISSUE THREAD

**Issue by TheChymera** [gentoo-science/sci#485]
While I was somehow able to get scipy and its deps (including blas, cblas and lapack) to install on some other systems (and I have not touched them since out of fear of breaking them...), I am having issues on a new system:

[This](https://bpaste.net/show/024b76cdc967) is the integral error log I get from portage, and my feeble attempts at debugging this with eselect and eix. To me it seems as if everything is in place, but portage for some reason does not see it.

Ideas?
@jlec ?

**Comment by kiwifb** [comment]
```
pkg-config blas --libs
```
?

**Comment by TheChymera** [comment]
gives me:

```
-lrefblas
```

**Comment by kiwifb** [comment]
Should have asked `pkg-config  --libs-only-l cblas blas` precisely. `blas` may be working but if `cblas` is not you'll get the failure.

**Comment by TheChymera** [comment]
Indeed, it seems the issue lies with cblas:

```
quiethost Downloads # pkg-config --libs-only-l cblas blas
Package cblas was not found in the pkg-config search path.
Perhaps you should add the directory containing `cblas.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cblas' found
quiethost Downloads # eselect cblas list
quiethost Downloads # 
```

**Comment by TheChymera** [comment]
@kiwifb so, what ca I do? (eix says I have cblas, cblas-reference, but is unsure `[?]` - even after an update - that I have eselect-cblas)

**Comment by kiwifb** [comment]
You certainly shouldn't have `eselect-cblas`. The `[?]` is usually meaning that the exact overlay from which the ebuild belongs too is uncertain. Can you show us the exact output?

**Comment by TheChymera** [comment]
```
quiethost Downloads # eix cblas
[?] app-eselect/eselect-cblas
     Available versions:  [m]0.1
     Installed versions:  0.1(01:36:54 03.07.2015)
     Homepage:            https://www.gentoo.org/proj/en/eselect/
     Description:         C-language BLAS module for eselect

[I] sci-libs/cblas-reference
     Available versions:  [m]20030223-r4 [m](~)20030223-r5 (~)20110218[2] (~)20110218[1] (~)20110218-r1[2] (~)20110218-r1[1] {int64 static-libs ABI_MIPS="n32 n64 o32" ABI_PPC="32 64" ABI_S390="32 64" ABI_X86="32 64 x32"}
     Installed versions:  20110218-r1[2](01:48:24 06.07.2015)(-int64 -static-libs ABI_MIPS="-n32 -n64 -o32" ABI_PPC="-32 -64" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")
     Homepage:            http://www.netlib.org/blas/
     Description:         C wrapper interface to the F77 reference BLAS implementation

[I] virtual/cblas
     Available versions:  [m]1.0 (~)2.0[2] (~)2.0[1] (~)2.0-r1[2] (~)2.0-r1[1] (~)2.0-r2[2] (~)2.0-r2[1] (~)2.0-r3[2] (~)2.0-r3[1] {int64 ABI_MIPS="n32 n64 o32" ABI_PPC="32 64" ABI_S390="32 64" ABI_X86="32 64 x32"}
     Installed versions:  2.0-r3[1](00:51:02 06.07.2015)(-int64 ABI_MIPS="-n32 -n64 -o32" ABI_PPC="-32 -64" ABI_S390="-32 -64" ABI_X86="64 -32 -x32")
     Description:         Virtual for BLAS C implementation

[1] "neurogentoo" /usr/local/portage/neurogentoo
[2] "science" /usr/local/portage/sci

Found 3 matches.
quiethost Downloads # 
```

do I just emerge -C it?

**Comment by kiwifb** [comment]
Never seen one in that position. Which probably means a problem in the database. Certainly try to unmerge it to see if it improves things.

**Comment by TheChymera** [comment]
this is what I get after unmerging it:

```
 * Package:    sci-libs/scipy-0.16.0
 * Repository: gentoo
 * Maintainer: sci@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python2_7 python_targets_python3_4 userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
 * Using following Fortran compiler:
 *   F77: x86_64-pc-linux-gnu-gfortran
 *   FC:  x86_64-pc-linux-gnu-gfortran
>>> Unpacking source...
>>> Unpacking scipy-0.16.0.tar.gz to /var/tmp/portage/sci-libs/scipy-0.16.0/work
>>> Source unpacked in /var/tmp/portage/sci-libs/scipy-0.16.0/work
>>> Preparing source in /var/tmp/portage/sci-libs/scipy-0.16.0/work/scipy-0.16.0 ...
Package cblas was not found in the pkg-config search path.
Perhaps you should add the directory containing `cblas.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cblas' found
Package cblas was not found in the pkg-config search path.
Perhaps you should add the directory containing `cblas.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cblas' found
Package cblas was not found in the pkg-config search path.
Perhaps you should add the directory containing `cblas.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cblas' found
 * Applying scipy-0.12.0-blitz.patch ...                                                                [ ok ]
 * Applying scipy-0.12.0-restore-sys-argv.patch ...                                                     [ ok ]
 * Will copy sources from /var/tmp/portage/sci-libs/scipy-0.16.0/work/scipy-0.16.0
 * python3_4: copying to /var/tmp/portage/sci-libs/scipy-0.16.0/work/scipy-0.16.0-python3_4
 * python2_7: copying to /var/tmp/portage/sci-libs/scipy-0.16.0/work/scipy-0.16.0-python2_7
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-libs/scipy-0.16.0/work/scipy-0.16.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sci-libs/scipy-0.16.0/work/scipy-0.16.0 ...
 * python3_4: running distutils-r1_run_phase python_compile
Processing scipy/signal/_spectral.pyx
Processing scipy/signal/_max_len_seq.pyx
Processing scipy/io/matlab/mio_utils.pyx
Processing scipy/io/matlab/mio5_utils.pyx
Processing scipy/io/matlab/streams.pyx
Processing scipy/cluster/_vq.pyx
Processing scipy/cluster/_hierarchy.pyx
Processing scipy/linalg/_solve_toeplitz.pyx
Processing scipy/linalg/cython_lapack.pyx
Processing scipy/linalg/cython_blas.pyx
Processing scipy/linalg/_decomp_update.pyx.in
Processing scipy/interpolate/_ppoly.pyx
Processing scipy/interpolate/interpnd.pyx
Processing scipy/ndimage/src/_ni_label.pyx
Processing scipy/spatial/qhull.pyx
Processing scipy/spatial/ckdtree/ckdtree.pyx
Processing scipy/special/_ellip_harm_2.pyx
Processing scipy/special/_ufuncs.pyx
Processing scipy/special/_ufuncs_cxx.pyx
Processing scipy/sparse/_csparsetools.pyx.in
Processing scipy/sparse/csgraph/_traversal.pyx
Processing scipy/sparse/csgraph/_min_spanning_tree.pyx
Processing scipy/sparse/csgraph/_reordering.pyx
Processing scipy/sparse/csgraph/_tools.pyx
Processing scipy/sparse/csgraph/_shortest_path.pyx
Processing scipy/stats/vonmises_cython.pyx
Processing scipy/stats/_rank.pyx
/usr/bin/python3.4 setup.py build config_fc --noopt --noarch
lapack_opt_info:
system_info:
  NOT AVAILABLE

lapack_info:
  FOUND:
    libraries = ['refblas', 'reflapack']
    language = f77
    library_dirs = ['/usr/lib64']

blas_info:
  libraries  not found in ['/usr/lib64']
  NOT AVAILABLE

blas_src_info:
  NOT AVAILABLE

  NOT AVAILABLE

/usr/lib64/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/usr/lib64/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/usr/lib64/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'setup_requires'
  warnings.warn(msg)
/usr/lib64/python3.4/site-packages/numpy/distutils/system_info.py:1486: UserWarning: 
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  warnings.warn(AtlasNotFoundError.__doc__)
/usr/lib64/python3.4/site-packages/numpy/distutils/system_info.py:575: UserWarning: Specified path  is invalid.
  warnings.warn('Specified path %s is invalid.' % d)
/usr/lib64/python3.4/site-packages/numpy/distutils/system_info.py:1510: UserWarning: 
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.
  warnings.warn(BlasNotFoundError.__doc__)
/usr/lib64/python3.4/site-packages/numpy/distutils/system_info.py:1513: UserWarning: 
    Blas (http://www.netlib.org/blas/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [blas_src]) or by setting
    the BLAS_SRC environment variable.
  warnings.warn(BlasSrcNotFoundError.__doc__)
Running from scipy source directory.
Traceback (most recent call last):
  File "setup.py", line 253, in <module>
    setup_package()
  File "setup.py", line 250, in setup_package
    setup(**metadata)
  File "/usr/lib64/python3.4/site-packages/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 175, in configuration
    config.add_subpackage('scipy')
  File "/usr/lib64/python3.4/site-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/usr/lib64/python3.4/site-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/usr/lib64/python3.4/site-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/setup.py", line 15, in configuration
    config.add_subpackage('linalg')
  File "/usr/lib64/python3.4/site-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
    caller_level = 2)
  File "/usr/lib64/python3.4/site-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
    caller_level = caller_level + 1)
  File "/usr/lib64/python3.4/site-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/linalg/setup.py", line 19, in configuration
    raise NotFoundError('no lapack/blas resources found')
numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
 * ERROR: sci-libs/scipy-0.16.0::gentoo failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_compile
 *   environment, line 4091:  Called distutils-r1_src_compile
 *   environment, line 1207:  Called _distutils-r1_run_foreach_impl 'python_compile'
 *   environment, line  365:  Called python_foreach_impl 'distutils-r1_run_phase' 'python_compile'
 *   environment, line 3542:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_compile'
 *   environment, line 2631:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_compile'
 *   environment, line 2629:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'python_compile'
 *   environment, line  807:  Called distutils-r1_run_phase 'python_compile'
 *   environment, line 1200:  Called python_compile
 *   environment, line 3144:  Called distutils-r1_python_compile 'config_fc' '--noopt' '--noarch'
 *   environment, line 1080:  Called esetup.py 'build' 'config_fc' '--noopt' '--noarch'
 *   environment, line 1688:  Called die
 * The specific snippet of code:
 *       "${@}" || die
 * 
 * If you need support, post the output of `emerge --info '=sci-libs/scipy-0.16.0::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=sci-libs/scipy-0.16.0::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/sci-libs/scipy-0.16.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-libs/scipy-0.16.0/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-libs/scipy-0.16.0/work/scipy-0.16.0-python3_4'
 * S: '/var/tmp/portage/sci-libs/scipy-0.16.0/work/scipy-0.16.0'
```

**Comment by kiwifb** [comment]
Well you are still without a cblas in eselect so that's totally expected. Re-emerge a `cblas` and check if it is properly registered in eselect or if there are any error messages about it.

**Comment by TheChymera** [comment]
@kiwifb thank you, after re-emerging cblas and running `eselect cblas set 1` (1 being gls) I could successfully emerge scipy.
