### ISSUE TITLE
lapack-reference-9999 build errors, due to the existence of a problem directory

### ISSUE THREAD

**Issue by fusion809** [gentoo-science/sci#492]
Hi,

I am desperate for someone to help me as I have been trying to install SageMath for like a week and every time I fail it's because of some package provided by this overlay is causing me grief. I have read [User talk:Houseofsuns](https://wiki.gentoo.org/wiki/User_talk:Houseofsuns) and tried it like half a dozen times so please don't direct me there again! This time when I tried to build `sci-libs/lapack-reference-9999` (although I should probably mention I was doing this with `emerge @preserved-rebuild`, if it is relevant) I got the error:

`Error: /var/tmp/portage/sci-libs/lapack-reference-9999/image//etc/env.d/alternatives/lapack/reference already present. You need ot remove it before adding it again`

I have tried removing the `/var/tmp/portage/sci-libs/lapack-reference-9999/image//etc/env.d/alternatives/lapack/reference` directory, but it does not stop this error message for popping up when I try to run `emerge @preserved-rebuild` again. I have also received this kind of error when I installed other versions of this package and `sci-libs/blas-reference-20131116`. 

Thanks for your time,
Brenton

**Comment by jlec** [comment]
How about simply using sci-libs/lapack-reference-3.5.0 ? We the live ebuild?

**Comment by kiwifb** [comment]
@jlec You missed the bit about being desperate. Do we have a plan to solve the issue?

**Comment by jlec** [comment]
I don't know what the problem is.

32bit ABIs are broken, but you don't need them anyways. I am working on a fix, but that means a complete rewrite of the eclass and all ebuilds.

**Comment by fusion809** [comment]
@jlec I have tried 3.5.0 too and it failed with similar errors.

**Comment by kiwifb** [comment]
> On 22/09/2015, at 20:17, Justin Lecher <notifications@github.com> wrote:
> 
> I don't know what the problem is.
> 

I am a bit mystified why some people cannot at least emerge a provider 
correctly as well.

> 32bit ABIs are broken, but you don't need them anyways.

Agree, the multilib is what breaks things when you want to remove provider,
but that was probably because the eclass was trying to be too smart.

> I am working on a fix, but that means a complete rewrite of the eclass and all ebuilds.
> 

Yurk! What kind of help do you need? Do you have some sort of design document?

François

**Comment by kiwifb** [comment]
@fusion809 one thing that may give a clue is passing `--debug` to `emerge` the problem is that the generated log is quite big and you would probably have to compress it and email it to one of us.  I believe my email is visible on github if you are tempted.

**Comment by fusion809** [comment]
So run `emerge --debug =sci-libs/lapack-reference-9999::science`? If so here it is http://pastebin.com/TNeYXV4D (using Pastebin instead of your email so that if anyone else has some ideas they can see my build.log file too).

**Comment by jlec** [comment]
Could you please provide a normal build.log too?

**Comment by fusion809** [comment]
Keeping in mind I had to install emerge `sci-libs/lapack-reference::gentoo` as a temporary solution so that I could install SageMath (although this install of SageMath is hardly perfect either, see [here](https://github.com/cschwan/sage-on-gentoo/issues/373)).

**Comment by fusion809** [comment]
[here](http://pastebin.com/7JijWSX7)'s my normal build.log

**Comment by jlec** [comment]
Just don't use ABI_X86="32"!

**Comment by fusion809** [comment]
How do I correct this? I'm at best an intermediate user of Sabayon, first started using it in July 2015. I understand USE flags, not this ABI stuff. Instead of running `emerge =sci-libs/lapack-reference-9999::science`, what do I do? Like do I add something like ABI_X86="64" before this command?

**Comment by kiwifb** [comment]
Usually those kind of things are stored in the file `/etc/portage/make.conf` if you want to disable it only for blas/cblas/lapack and co that will be a bit more complicated but `/etc/portage` will be where it's at.

**Comment by jlec** [comment]
@fusion809 check that in your make.conf you don't have ```ABI_X86="32"``` and not set ```USE=abi_86_32``` for any of blas/lapack and such.

**Comment by fusion809** [comment]
I made this modification to make.conf (changing the line from ABI_X86="64 32" to ABI_X86="64") and re-ran `emerge =sci-libs/lapack-reference-9999:science` but this gave the error:

```sh
>>> Emerging (2 of 3) sci-libs/lapack-reference-9999::science
 * Using following Fortran compiler:
 *   F77: x86_64-pc-linux-gnu-gfortran
 *   FC:  x86_64-pc-linux-gnu-gfortran
>>> Unpacking source...
 * Fetching https://github.com/nschloe/lapack.git ...
git fetch https://github.com/nschloe/lapack.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/sci-libs/lapack-reference/0/__main__ refs/heads/master
 * Checking out https://github.com/nschloe/lapack.git to /var/tmp/portage/sci-libs/lapack-reference-9999/work/lapack-reference-9999 ...
git checkout --quiet master
GIT update -->
   repository:               https://github.com/nschloe/lapack.git
   at the commit:            8267c67b34e7907b7add90c19730b9a3d5dde0ef
>>> Source unpacked in /var/tmp/portage/sci-libs/lapack-reference-9999/work
>>> Preparing source in /var/tmp/portage/sci-libs/lapack-reference-9999/work/lapack-reference-9999 ...
!!! Error: Action files unknown
exiting
Must specify package names on the command line
 * ERROR: sci-libs/lapack-reference-9999::science failed (prepare phase):
 *   lapack-reference requires the pkgbuild module 
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_prepare
 *   environment, line 4065:  Called fortran-int64_ensure_blas
 *   environment, line 1998:  Called die
 * The specific snippet of code:
 *           $(tc-getPKG_CONFIG) --exists "${blas_profname}" || die "${PN} requires the pkgbuild module ${blas_profname}";
 * 
 * If you need support, post the output of `emerge --info '=sci-libs/lapack-reference-9999::science'`,
 * the complete build log and the output of `emerge -pqv '=sci-libs/lapack-reference-9999::science'`.
 * The complete build log is located at '/var/tmp/portage/sci-libs/lapack-reference-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-libs/lapack-reference-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-libs/lapack-reference-9999/work/lapack-reference-9999'
 * S: '/var/tmp/portage/sci-libs/lapack-reference-9999/work/lapack-reference-9999'

>>> Failed to emerge sci-libs/lapack-reference-9999, Log file:

>>>  '/var/tmp/portage/sci-libs/lapack-reference-9999/temp/build.log'

 * Messages for package sci-libs/blas-reference-20131116-r1:

 * This package will overwrite one or more files that may belong to other
 * packages (see list below). You can use a command such as `portageq
 * owners / <filename>` to identify the installed package that owns a
 * file. If portageq reports that only one package owns a file then do
 * NOT file a bug report. A bug report is only useful if it identifies at
 * least two or more packages that are known to install the same file(s).
 * If a collision occurs and you can not explain where the file came from
 * then you should simply ignore the collision since there is not enough
 * information to determine if a real problem exists. Please do NOT file
 * a bug report at http://bugs.gentoo.org unless you report exactly which
 * two packages install the same file(s). See
 * http://wiki.gentoo.org/wiki/Knowledge_Base:Blockers for tips on how to
 * solve the problem. And once again, please do NOT file a bug report
 * unless you have completely understood the above message.
 * 
 * Detected file collision(s):
 * 
 *      /usr/lib/debug/usr/lib64/librefblas.so.debug
 *      /usr/lib64/librefblas.so
 *      /usr/lib64/pkgconfig/refblas.pc
 *      /etc/env.d/alternatives/blas/reference/_importance
 *      /etc/env.d/alternatives/blas/reference/usr/lib64/pkgconfig/blas.pc
 * 
 * Searching all installed packages for file collisions...
 * 
 * Press Ctrl-C to Stop
 * 
 * None of the installed packages claim the file(s).
 * 
 * Package 'sci-libs/blas-reference-20131116-r1' merged despite file
 * collisions. If necessary, refer to your elog messages for the whole
 * content of the above message.

 * Messages for package sci-libs/lapack-reference-9999:

 * ERROR: sci-libs/lapack-reference-9999::science failed (prepare phase):
 *   lapack-reference requires the pkgbuild module 
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_prepare
 *   environment, line 4065:  Called fortran-int64_ensure_blas
 *   environment, line 1998:  Called die
 * The specific snippet of code:
 *           $(tc-getPKG_CONFIG) --exists "${blas_profname}" || die "${PN} requires the pkgbuild module ${blas_profname}";
 * 
 * If you need support, post the output of `emerge --info '=sci-libs/lapack-reference-9999::science'`,
 * the complete build log and the output of `emerge -pqv '=sci-libs/lapack-reference-9999::science'`.
 * The complete build log is located at '/var/tmp/portage/sci-libs/lapack-reference-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-libs/lapack-reference-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-libs/lapack-reference-9999/work/lapack-reference-9999'
 * S: '/var/tmp/portage/sci-libs/lapack-reference-9999/work/lapack-reference-9999'
 * waiting for lock on /var/db/.pkg.portage_lockfile ...                
```

**Comment by fusion809** [comment]
[here](http://pastebin.com/H2j13fnN)'s my build.log file.

**Comment by kiwifb** [comment]
OK the failure in `lapack` is because of problems that occurred during the merge `blas`. Make sure that `blas-reference` is unmerge (`emerge -C blas-reference`). Then remove those files manually if they are present:
```
/usr/lib/debug/usr/lib64/librefblas.so.debug
/usr/lib64/librefblas.so
/usr/lib64/pkgconfig/refblas.pc
/etc/env.d/alternatives/blas/reference/_importance
/etc/env.d/alternatives/blas/reference/usr/lib64/pkgconfig/blas.pc
```
And please don't use `9999` ebuilds unless you really know what you are doing.

**Comment by fusion809** [comment]
I tried emerging lapack-reference-3.5.0 instead, after I had deleted all the files you listed that were present and I got the error:

```sh
>>> Emerging (1 of 2) sci-libs/lapack-reference-3.5.0::science
 * lapack-3.5.0.tgz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                              [ ok ]
 * Using following Fortran compiler:
 *   F77: x86_64-pc-linux-gnu-gfortran
 *   FC:  x86_64-pc-linux-gnu-gfortran
>>> Unpacking source...
>>> Unpacking lapack-3.5.0.tgz to /var/tmp/portage/sci-libs/lapack-reference-3.5.0/work
>>> Source unpacked in /var/tmp/portage/sci-libs/lapack-reference-3.5.0/work
>>> Preparing source in /var/tmp/portage/sci-libs/lapack-reference-3.5.0/work/lapack-3.5.0 ...
!!! Error: Action files unknown
exiting
Must specify package names on the command line
 * ERROR: sci-libs/lapack-reference-3.5.0::science failed (prepare phase):
 *   lapack-reference requires the pkgbuild module 
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_prepare
 *   environment, line 3522:  Called fortran-int64_ensure_blas
 *   environment, line 1792:  Called die
 * The specific snippet of code:
 *           $(tc-getPKG_CONFIG) --exists "${blas_profname}" || die "${PN} requires the pkgbuild module ${blas_profname}";
 * 
 * If you need support, post the output of `emerge --info '=sci-libs/lapack-reference-3.5.0::science'`,
 * the complete build log and the output of `emerge -pqv '=sci-libs/lapack-reference-3.5.0::science'`.
 * The complete build log is located at '/var/tmp/portage/sci-libs/lapack-reference-3.5.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-libs/lapack-reference-3.5.0/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-libs/lapack-reference-3.5.0/work/lapack-3.5.0'
 * S: '/var/tmp/portage/sci-libs/lapack-reference-3.5.0/work/lapack-3.5.0'

>>> Failed to emerge sci-libs/lapack-reference-3.5.0, Log file:

>>>  '/var/tmp/portage/sci-libs/lapack-reference-3.5.0/temp/build.log'

 * Messages for package sci-libs/lapack-reference-3.5.0:

 * ERROR: sci-libs/lapack-reference-3.5.0::science failed (prepare phase):
 *   lapack-reference requires the pkgbuild module 
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_prepare
 *   environment, line 3522:  Called fortran-int64_ensure_blas
 *   environment, line 1792:  Called die
 * The specific snippet of code:
 *           $(tc-getPKG_CONFIG) --exists "${blas_profname}" || die "${PN} requires the pkgbuild module ${blas_profname}";
 * 
 * If you need support, post the output of `emerge --info '=sci-libs/lapack-reference-3.5.0::science'`,
 * the complete build log and the output of `emerge -pqv '=sci-libs/lapack-reference-3.5.0::science'`.
 * The complete build log is located at '/var/tmp/portage/sci-libs/lapack-reference-3.5.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-libs/lapack-reference-3.5.0/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-libs/lapack-reference-3.5.0/work/lapack-3.5.0'
 * S: '/var/tmp/portage/sci-libs/lapack-reference-3.5.0/work/lapack-3.5.0'
```

**Comment by fusion809** [comment]
If it helps here's my existing preserved libs:

```sh
>>> package: x11-misc/lightdm-base-1.14.2
 *  - /usr/lib64/liblightdm-gobject-1.so.0
 *  - /usr/lib64/liblightdm-gobject-1.so.0.0.0
 *      used by /usr/lib64/liblightdm-qt-3.so.0.0.0 (x11-misc/lightdm-qt4-1.14.2)
 *      used by /usr/sbin/lightdm-gtk-greeter (x11-misc/lightdm-gtk-greeter-2.0.1)
 *      used by /usr/sbin/pantheon-greeter (pantheon-base/pantheon-greeter-2.0.2)
>>> package: sci-libs/blas-reference-20131116-r1
 *  - /usr/lib64/librefblas.so
 *      used by /usr/lib64/blas/reference/libcblas.so.0.0.0 (sci-libs/cblas-reference-20030223-r5)
 *      used by /usr/lib64/lapack/reference/liblapack.so.0.0.0 (sci-libs/lapack-reference-3.2.1-r1)
 *      used by /usr/lib64/libarpack.so.2.0.0 (sci-libs/arpack-3.1.5)
 *      used by 11 other files
 *  - /usr/lib64/blas/reference/libblas.so.0
 *  - /usr/lib64/blas/reference/libblas.so.0.0.0
 *      used by /usr/bin/scilab-bin (sci-mathematics/scilab-5.5.2-r1)
 *      used by /usr/bin/scilab-cli-bin (sci-mathematics/scilab-5.5.2-r1)
 *      used by /usr/lib64/scilab/libjavasci2.so.5.5.2 (sci-mathematics/scilab-5.5.2-r1)
 *      used by 3 other files
```

**Comment by kiwifb** [comment]
Is `blas-reference` properly emerged? If so what does `eselect blas list` report? Do you have a `blas` properly "eselected"?

**Comment by fusion809** [comment]
`eselect blas list` gives no output, I'm guessing that means I need to emerge `blas-eselect`?

**Comment by kiwifb** [comment]
You will have to re-emerge `blas-reference` I believe.

**Comment by fusion809** [comment]
This is odd emerging `blas-reference` gives:

```sh
>>> Installing (1 of 1) sci-libs/blas-reference-20131116-r1::science
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/portage/dbapi/_MergeProcess.py", line 235, in _spawn
    prev_mtimes=self.prev_mtimes, counter=counter)
  File "/usr/lib64/python2.7/site-packages/portage/dbapi/vartree.py", line 5006, in merge
    counter=counter)
  File "/usr/lib64/python2.7/site-packages/portage/dbapi/vartree.py", line 4246, in treewalk
    preserve_paths=preserve_paths)
  File "/usr/lib64/python2.7/site-packages/portage/dbapi/vartree.py", line 2002, in unmerge
    preserve_paths=preserve_paths)
  File "/usr/lib64/python2.7/site-packages/portage/dbapi/vartree.py", line 1842, in _prune_plib_registry
    unmerge_no_replacement)
  File "/usr/lib64/python2.7/site-packages/portage/dbapi/vartree.py", line 3172, in _find_unused_preserved_libs
    for c in self.vartree.dbapi._linkmap.findConsumers(f):
  File "/usr/lib64/python2.7/site-packages/portage/util/_dyn_libs/LinkageMapELF.py", line 778, in findConsumers
    raise KeyError("%s (%s) not in object list" % (obj_key, obj))
KeyError: u'<portage.util._dyn_libs.LinkageMapELF._ObjectKey object at 0x7f4634b19a60> (/usr/lib64/blas/reference/libblas.so.0.0.0) not in object list'

>>> Failed to install sci-libs/blas-reference-20131116-r1, Log file:

>>>  '/var/tmp/portage/sci-libs/blas-reference-20131116-r1/temp/build.log'
```

at the install stage.

**Comment by fusion809** [comment]
[here](http://pastebin.com/3xDDTtsU)'s my log file if it helps.

**Comment by kiwifb** [comment]
Hum yes you are back with stuff from the main tree. portage expects that merging `blas-reference` will solve the problem preserved-libraries but it doesn't in this case. You will have to re-emerge all blas dependencies in any case.
First let's try to just remove `/usr/lib64/blas/reference/libblas.so.0.0.0` manually and if that helps merging. If not my recommendation is un-merging all the packages depending on `blas` before retrying.

**Comment by fusion809** [comment]
After removing that file I got a different error when I emerged blas-reference:

```sh
>>> Installing (1 of 1) sci-libs/blas-reference-20131116-r1::science
!!! Error: Action update unknown
exiting
 * eselect blas update  returned 
!!! Error: File "//etc/env.d/blas/lib64/reference" is missing!
Call stack:
    * iface_do_show (skel.bash:143)
    * do_show (skel.bash:283)
    * check_do (core.bash:24)
    * do_action (core.bash:105)
    * main (eselect:309)
exiting
 * Creating Alternative for blas
!!! Error: Action update unknown
exiting
```

if I have to unmerge all packages depending on blas I think I'll just stick with the older version of blas-reference provided by the main Gentoo overlay.
