### ISSUE TITLE
dev-python/rpy-2.7.6::gentoo can't find libblas

### ISSUE THREAD

**Issue by chi86** [gentoo-science/sci#560]
dev-python/rpy-2.7.6::gentoo can't find libblas. I looked it up and it is really not there. I set
```
eselect blas set reference
```
and I remergerd all needed packages based on "https://wiki.gentoo.org/wiki/User_talk:Houseofsuns".

The error message from dev-python/rpy-2.7.6:
```
>>> Emerging (2 of 3) dev-python/rpy-2.7.6::gentoo
 * rpy2-2.7.6.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                         [ ok ]
No protected directories found...
>>> cfg-update-1.8.2-r1: Creating checksum index...
>>> Unpacking source...
>>> Unpacking rpy2-2.7.6.tar.gz to /var/tmp/portage/dev-python/rpy-2.7.6/work
>>> Source unpacked in /var/tmp/portage/dev-python/rpy-2.7.6/work
>>> Preparing source in /var/tmp/portage/dev-python/rpy-2.7.6/work/rpy2-2.7.6 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/rpy-2.7.6/work/rpy2-2.7.6 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/rpy-2.7.6/work/rpy2-2.7.6 ...
 * python2_7: running distutils-r1_run_phase python_compile
/usr/bin/python2.7 setup.py build
/usr/lib64/R/bin/exec/R: error while loading shared libraries: libblas.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "setup.py", line 291, in <module>
    ri_ext = getRinterface_ext()
  File "setup.py", line 194, in getRinterface_ext
    if rexec.version[0] == 'development' or \
  File "setup.py", line 120, in version
    universal_newlines = True)
  File "/usr/lib64/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('/usr/lib64/R/bin/R', '--version')' returned non-zero exit status 127
 * ERROR: dev-python/rpy-2.7.6::gentoo failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line   90:  Called src_compile
 *   environment, line 3943:  Called distutils-r1_src_compile
 *   environment, line 1066:  Called _distutils-r1_run_foreach_impl 'python_compile'
 *   environment, line  354:  Called python_foreach_impl 'distutils-r1_run_phase' 'python_compile'
 *   environment, line 3402:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_compile'
 *   environment, line 2491:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_compile'
 *   environment, line 2489:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'python_compile'
 *   environment, line  665:  Called distutils-r1_run_phase 'python_compile'
 *   environment, line 1059:  Called python_compile
 *   environment, line 2990:  Called distutils-r1_python_compile
 *   environment, line  931:  Called esetup.py 'build'
 *   environment, line 1554:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}" || return ${?}
 * 
 * If you need support, post the output of `emerge --info '=dev-python/rpy-2.7.6::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/rpy-2.7.6::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-python/rpy-2.7.6/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-python/rpy-2.7.6/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-python/rpy-2.7.6/work/rpy2-2.7.6'
 * S: '/var/tmp/portage/dev-python/rpy-2.7.6/work/rpy2-2.7.6'
```
I know it is not directly related to the gentoo-sci but I think the issue is the missing libblas.
How would i get the missing library back?

**Comment by marbre** [comment]
Looks like `/usr/lib64/R/bin/exec/R` is still linked against `libblas.so.0`. This is the lib from portage, the one provided by science overlay is named `librefblas.so.3`. Check (using `equery` for example) to which package the executable belongs (probably  `dev-lang/R`) and re-emerge this specific package.

**Comment by kiwifb** [comment]
I guess the page should be updated (and possibly made more visible). The page says to use `revdep-rebuild` but rebuilding the output of `equery -q d blas cblas lapack | sort -u` may be more complete.

**Comment by marbre** [comment]
@kiwifb You're right. Unfortunately not all packages directly depend on blas/lapack. For example `sci-libs/scikits_learn` depends on `numpy[lapack]`, but not on `virtual/lapack`. Anyway, the _k_means.so (or similar) is linked to the blas library. Thus the dependencies need to be fixed, to let this approach work.

I recently used a bash script to checked all *.so files in /usr/lib64 with ldd and grep, looking for a specific lapack implementation which I wanted to get rid of. I hopefully find some time to take care of the dependencies.

**Comment by kiwifb** [comment]
If it is linked directly it should at least be in `RDEPEND`. `equery d -D` also can spot indirect dependencies, there is another switch for the depth but I wouldn't want to go more than one or two steps beyond what's in the `{R,P}DEPEND` variables.

**Comment by chi86** [comment]
thx that worked perfectly :+1:

**Comment by marbre** [comment]
Glad that this hint fixed it. Closing the issue therefore.
